### ISSUE TITLE
Práctica 7: App con funcionalidades de RA alojados a un hosting

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-gps-equipo_prestadores-de-servicios#2]
[Práctica 7_ Despliegue de App a un hosting..pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-equipo_prestadores-de-servicios/files/8604984/Practica.7_.Despliegue.de.App.a.un.hosting.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Buen trabajo
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
